### ISSUE TITLE
Реализовать возможность открытие лог-файла через "Открыть"

### ISSUE THREAD

**Issue by chepelda** [DirectumCompany/DirectumLogViewer#2]
Порядок действий 1:
* Назначить LogViewer, как обработчик расширения файлов log
* Открыть файл средствами операционной системы

Порядок действий 2:
* LogViewer.exe <имя_файла_логов>

Наблюдаемый результат:
* Открывается LogViewer, выбранный лог-файл не подхватывается

Ожидаемый результат:
* LogViewer открывает указанный файл

**Comment by desol8686** [comment]
Реализовано
