### ISSUE TITLE
При открытии нового лога сбрасывает фильтр

### ISSUE THREAD

**Issue by igel2000** [DirectumCompany/DirectumLogViewer#6]
Это не очень хорошо для двух ситуаций:
1. Отладка какой-то разработки через добавление в лог debug-сообщений. Нередко в этом задействован код, который выполняется на нескольких сервисах - вбе-доступ, worker, сервисы WF. В этом случае нужно последовательно открывать несколько логов и каждый раз накладывать фильтр.
2. Если разработчик/администратор не очень хорошо представляет какой код в каком сервисе выполняется, то при поиске лога какой-то ошибки ему приходится искать это перебирая логи и добавляя в фильтр Error. А для админов и разрабочиков первого года это типичная ситуация, когда не могут четко понять в каком логе искать надо.

**Comment by desol8686** [comment]
исправлено
